[toolchain]
channel = "1.85.0"
components = ["rustfmt", "clippy"]
targets = [
  "aarch64-linux-android",
  "armv7-linux-androideabi",
  "i686-linux-android",
  "x86_64-linux-android",
  "aarch64-apple-ios",
  "aarch64-apple-ios-sim",
  "wasm32-unknown-unknown",
]
